version: '3.9'

services:
  web:
    container_name: simple-npm-update-cont
    build:
      context: .
      dockerfile: Dockerfile
    command: bash deployment.sh
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tm4netmicro

  db:
    container_name: redis-micro-simple-npm-cont
    image: redis:7.0-rc2
    command: redis-server --requirepass tm4law
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tm4netmicro

networks:
  tm4netmicro:
    name: tm4netmicro

volumes:
  redis_data:
    name: tm4dbmicro